apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-duckdns
spec:
  acme:
    email: ubaidullah244@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-duckdns-private-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.duckdns.org
          solverName: duckdns
          config:
            tokenSecretRef:
              name: duckdns-api-secret
              key: token
