apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aboss-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-duckdns
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - aboss-demo.duckdns.org
    secretName: aboss-demo-tls
  rules:
  - host: aboss-demo.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aboss-demo-service
            port:
              number: 80
