apiVersion: v1
kind: Service
metadata:
  name: aboss-demo-service
  labels:
    app: aboss-demo-service
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: aboss-spam-check
  type: ClusterIP
