apiVersion: apps/v1
kind: Deployment
metadata:
  name: aboss-spam-check
  labels:
    app: aboss-spam-check
spec:
  replicas: {{.Values.deploy_replicas_count}}
  selector:
    matchLabels:
      app: aboss-spam-check
  template:
    metadata:
      labels:
        app: aboss-spam-check
    spec:
      containers:
      - name: aboss-spam-check
        image: ubaidullah244/spam_check:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
